name: Fast DDS Ubuntu CI - Fast DDS test

on:
  workflow_call:
    inputs:
      os-image:
        description: 'The OS image for the workflow'
        required: true
        type: string
      label:
        description: 'ID associated to the workflow'
        required: true
        type: string
      colcon-args:
        description: 'Extra arguments for colcon cli'
        required: false
        type: string
      cmake-args:
        description: 'Extra arguments for cmake cli'
        required: false
        type: string
      ctest-args:
        description: 'Extra arguments for ctest cli'
        required: false
        type: string
      fastdds-branch:
        description: 'Branch or tag of Fast DDS repository (https://github.com/eProsima/Fast-DDS)'
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  fastdds_build_test:
    runs-on: ${{ inputs.os-image }}
    if: ${{ (
          !contains(github.event.pull_request.labels.*.name, 'skip-ci') &&
          !contains(github.event.pull_request.labels.*.name, 'no-test') &&
          !contains(github.event.pull_request.labels.*.name, 'conflicts')
        ) }}
    steps:
      - name: Download build artifacts
        uses: eProsima/eProsima-CI/external/download-artifact@v0
        with:
          name: fastdds_build_${{ inputs.label }}
          path: ${{ github.workspace }}

      - name: Install Fix Python version
        uses: eProsima/eProsima-CI/external/setup-python@v0
        with:
          python-version: '3.11'

      - name: Get minimum supported version of CMake
        uses: eProsima/eProsima-CI/external/get-cmake@v0
        with:
          cmakeVersion: '3.22.6'

      - name: Install apt packages
        uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@v0
        with:
          packages: libasio-dev libtinyxml2-dev libssl-dev

      - name: Install colcon
        uses: eProsima/eProsima-CI/ubuntu/install_colcon@v0

      - name: Install Python dependencies
        uses: eProsima/eProsima-CI/ubuntu/install_python_packages@v0
        with:
          packages: xmlschema

      - name: Setup CCache
        uses: eProsima/eProsima-CI/external/setup-ccache-action@v0

      - name: Set up hosts file for DNS testing
        run: |
          sudo echo "" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 localhost.test" | sudo tee -a /etc/hosts
          sudo echo "::1 localhost.test" | sudo tee -a /etc/hosts
          sudo echo "154.56.134.194 www.eprosima.com.test" | sudo tee -a /etc/hosts
          sudo echo "216.58.215.164 www.acme.com.test" | sudo tee -a /etc/hosts
          sudo echo "2a00:1450:400e:803::2004 www.acme.com.test" | sudo tee -a /etc/hosts
          sudo echo "140.82.121.4 www.foo.com.test" | sudo tee -a /etc/hosts
          sudo echo "140.82.121.3 www.foo.com.test" | sudo tee -a /etc/hosts
          sudo echo "ff1e::ffff:efff:1 acme.org.test" | sudo tee -a /etc/hosts

      - name: Colcon build
        continue-on-error: false
        uses: eProsima/eProsima-CI/multiplatform/colcon_build@v0
        with:
          colcon_meta_file: ${{ github.workspace }}/src/fastdds/.github/workflows/config/ci.meta
          colcon_build_args: ${{ inputs.colcon-args }}
          cmake_args: ${{ inputs.cmake-args }}
          cmake_args_default: -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra -Wpedantic -Wunused-value -Woverloaded-virtual" -DFASTDDS_EXAMPLE_TESTS=ON
          cmake_build_type: ${{ matrix.cmake-build-type }}
          workspace: ${{ github.workspace }}

      - name: Colcon test
        id: test
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-test') }}
        uses: eProsima/eProsima-CI/multiplatform/colcon_test@v0
        with:
          colcon_test_args: ${{ inputs.colcon-args }}
          colcon_test_args_default: --event-handlers=console_direct+
          ctest_args: ${{ inputs.ctest-args }}
          ctest_args_default: --repeat until-pass:3 --timeout 300 --label-exclude "xfail"
          packages_names: fastdds
          workspace: ${{ github.workspace }}
          test_report_artifact: ${{ format('test_report_{0}_{1}_{2}', inputs.label, github.job, join(matrix.*, '_')) }}

      - name: Fast DDS test summary
        uses: eProsima/eProsima-CI/multiplatform/junit_summary@v0
        if: ${{ !cancelled() && !contains(github.event.pull_request.labels.*.name, 'no-test') }}
        with:
          junit_reports_dir: "${{ steps.test.outputs.ctest_results_path }}"
          print_summary: 'True'
          show_failed: 'True'
          show_disabled: 'False'
          show_skipped: 'False'
