name: Fast DDS Ubuntu CI - Fast DDS build

on:
  workflow_call:
    inputs:
      os-image:
        description: 'The OS image for the workflow'
        required: true
        type: string
      label:
        description: 'ID associated to the workflow'
        required: true
        type: string
      colcon-args:
        description: 'Extra arguments for colcon cli'
        required: false
        type: string
      cmake-args:
        description: 'Extra arguments for cmake cli'
        required: false
        type: string
      ctest-args:
        description: 'Extra arguments for ctest cli'
        required: false
        type: string
      fastdds-branch:
        description: 'Branch or tag of Fast DDS repository (https://github.com/eProsima/Fast-DDS)'
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  fastdds_build:
    runs-on: ${{ inputs.os-image }}
    if: ${{ (
          !contains(github.event.pull_request.labels.*.name, 'skip-ci') &&
          !contains(github.event.pull_request.labels.*.name, 'conflicts')
        ) }}
    strategy:
      fail-fast: false
      matrix:
        cmake-build-type:
          - 'RelWithDebInfo'
    steps:
      - name: Add ci-pending label if PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: eProsima/eProsima-CI/external/add_labels@v0
        with:
          labels: ci-pending
          number: ${{ github.event.number }}
          repo: eProsima/Fast-DDS

      - name: Sync eProsima/Fast-DDS repository
        uses: eProsima/eProsima-CI/external/checkout@v0
        with:
          path: src/fastdds
          ref: ${{ inputs.fastdds-branch }}

      - name: Install Fix Python version
        uses: eProsima/eProsima-CI/external/setup-python@v0
        with:
          python-version: '3.11'

      - name: Get minimum supported version of CMake
        uses: eProsima/eProsima-CI/external/get-cmake@v0
        with:
          cmakeVersion: '3.22.6'

      - name: Install apt dependencies
        uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@v0
        with:
          packages: libasio-dev libtinyxml2-dev libssl-dev
          update: false
          upgrade: false

      - name: Install colcon
        uses: eProsima/eProsima-CI/ubuntu/install_colcon@v0

      - name: Install Python dependencies
        uses: eProsima/eProsima-CI/multiplatform/install_python_packages@v0
        with:
          packages: vcstool xmlschema
          upgrade: false

      - name: Setup CCache
        uses: eProsima/eProsima-CI/external/setup-ccache-action@v0

      # TODO(eduponz): Set up libp11 and SoftHSM. NOTE: using SoftHSM requires adding the runner to a group,
      #                which entails logout/login or rebooting the machine. This is not feasible in a CI environment.

      - name: Fetch Fast DDS dependencies
        uses: eProsima/eProsima-CI/multiplatform/vcs_import@v0
        with:
          vcs_repos_file: ${{ github.workspace }}/src/fastdds/fastdds.repos
          destination_workspace: src
          skip_existing: 'true'

      - name: Fetch Fast DDS CI dependencies
        uses: eProsima/eProsima-CI/multiplatform/vcs_import@v0
        with:
          vcs_repos_file: ${{ github.workspace }}/src/fastdds/.github/workflows/config/ci.repos
          destination_workspace: src
          skip_existing: 'true'

      - name: Colcon build
        continue-on-error: false
        uses: eProsima/eProsima-CI/multiplatform/colcon_build@v0
        with:
          colcon_meta_file: ''
          colcon_build_args: ${{ inputs.colcon-args }}
          cmake_args: ${{ inputs.cmake-args }}
          cmake_args_default: -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra -Wpedantic -Wunused-value -Woverloaded-virtual"
          cmake_build_type: ${{ matrix.cmake-build-type }}
          workspace: ${{ github.workspace }}

      - name: Upload build artifacts
        uses: eProsima/eProsima-CI/external/upload-artifact@v0
        with:
          name: fastdds_build_${{ inputs.label }}
          path: ${{ github.workspace }}
