name: Fast DDS Ubuntu CI - Fast DDS Discovery Server build test

on:
  workflow_call:
    inputs:
      os-image:
        description: 'The OS image for the workflow'
        required: true
        type: string
      label:
        description: 'ID associated to the workflow'
        required: true
        type: string
      colcon-args:
        description: 'Extra arguments for colcon cli'
        required: false
        type: string
      cmake-args:
        description: 'Extra arguments for cmake cli'
        required: false
        type: string
      ctest-args:
        description: 'Extra arguments for ctest cli'
        required: false
        type: string
      fastdds-branch:
        description: 'Branch or tag of Fast DDS repository (https://github.com/eProsima/Fast-DDS)'
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  fastdds_discovery_server_build_test:
    needs: fastdds_build

    if: ${{ (
          !contains(github.event.pull_request.labels.*.name, 'skip-ci') &&
          !contains(github.event.pull_request.labels.*.name, 'conflicts')
        ) }}
    runs-on: ${{ inputs.os-image }}
    strategy:
      fail-fast: false
      matrix:
        cmake-build-type:
          - 'RelWithDebInfo'
    steps:
      - name: Download build artifacts
        uses: eProsima/eProsima-CI/external/download-artifact@v0
        with:
          name: fastdds_build_${{ inputs.label }}
          path: ${{ github.workspace }}

      - name: Install Fix Python version
        uses: eProsima/eProsima-CI/external/setup-python@v0
        with:
          python-version: '3.11'

      - name: Get minimum supported version of CMake
        uses: eProsima/eProsima-CI/external/get-cmake@v0
        with:
          cmakeVersion: '3.22.6'

      - name: Install apt packages
        uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@v0
        with:
          packages: libasio-dev libtinyxml2-dev libssl-dev

      - name: Install colcon
        uses: eProsima/eProsima-CI/ubuntu/install_colcon@v0

      - name: Install Python dependencies
        uses: eProsima/eProsima-CI/ubuntu/install_python_packages@v0
        with:
          packages: xmlschema

      - name: Setup CCache
        uses: eProsima/eProsima-CI/external/setup-ccache-action@v0

      - name: Get Discovery Server branch
        id: get_discovery_server_branch
        uses: eProsima/eProsima-CI/ubuntu/get_related_branch_from_repo@v0
        with:
          remote_repository: eProsima/Discovery-Server
          fallback_branch: 'master'

      - name: Download Discovery Server repo
        uses: eProsima/eProsima-CI/external/checkout@v0
        with:
          repository: eProsima/Discovery-Server
          path: src/discovery_server
          ref: ${{ steps.get_discovery_server_branch.outputs.deduced_branch }}

      - name: Colcon build
        continue-on-error: false
        uses: eProsima/eProsima-CI/multiplatform/colcon_build@v0
        with:
          colcon_meta_file: ${{ github.workspace }}/src/fastdds/.github/workflows/config/ci.meta
          colcon_build_args: '${{ inputs.colcon-args }} --packages-up-to discovery-server'
          cmake_args: ${{ inputs.cmake-args }}
          cmake_args_default: -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra -Wpedantic -Wunused-value -Woverloaded-virtual"
          cmake_build_type: ${{ matrix.cmake-build-type }}
          workspace: ${{ github.workspace }}

      - name: Colcon test
        id: discovery_server_test
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-test') }}
        uses: eProsima/eProsima-CI/multiplatform/colcon_test@v0
        with:
          colcon_test_args: ${{ inputs.colcon-args }}
          colcon_test_args_default: --event-handlers=console_direct+
          ctest_args: ${{ inputs.ctest-args }}
          ctest_args_default: --repeat until-pass:3 --timeout 300 --label-exclude "xfail"
          packages_names: discovery-server
          workspace: ${{ github.workspace }}
          workspace_dependencies: ''
          test_report_artifact: ${{ format('test_report_{0}_{1}_{2}', inputs.label, github.job, join(matrix.*, '_')) }}

      - name: Discovery server test summary
        uses: eProsima/eProsima-CI/multiplatform/junit_summary@v0
        if: ${{ !cancelled() && !contains(github.event.pull_request.labels.*.name, 'no-test') }}
        with:
          junit_reports_dir: "${{ steps.discovery_server_test.outputs.ctest_results_path }}"
          print_summary: 'True'
          show_failed: 'True'
          show_disabled: 'False'
          show_skipped: 'False'
