name: Fast DDS Ubuntu CI - Fast DDS Docs build test

on:
  workflow_call:
    inputs:
      os-image:
        description: 'The OS image for the workflow'
        required: true
        type: string
      label:
        description: 'ID associated to the workflow'
        required: true
        type: string
      colcon-args:
        description: 'Extra arguments for colcon cli'
        required: false
        type: string
      cmake-args:
        description: 'Extra arguments for cmake cli'
        required: false
        type: string
      ctest-args:
        description: 'Extra arguments for ctest cli'
        required: false
        type: string
      fastdds-branch:
        description: 'Branch or tag of Fast DDS repository (https://github.com/eProsima/Fast-DDS)'
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  fastdds_docs_build_test:
    runs-on: ${{ inputs.os-image }}
    if: ${{ (
          !contains(github.event.pull_request.labels.*.name, 'skip-ci') &&
          !contains(github.event.pull_request.labels.*.name, 'conflicts')
        ) }}
    strategy:
      fail-fast: false
      matrix:
        cmake-build-type:
          - 'RelWithDebInfo'
    steps:
      - name: Download python build artifacts
        uses: eProsima/eProsima-CI/external/download-artifact@v0
        with:
          name: fastdds_python_build_${{ inputs.label }}
          path: ${{ github.workspace }}

      - name: Install Fix Python version
        uses: eProsima/eProsima-CI/external/setup-python@v0
        with:
          python-version: '3.11'

      - name: Get minimum supported version of CMake
        uses: eProsima/eProsima-CI/external/get-cmake@v0
        with:
          cmakeVersion: '3.22.6'

      - name: Install apt packages
        uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@v0
        with:
          packages: libasio-dev libtinyxml2-dev libssl-dev swig doxygen imagemagick plantuml

      - name: Install colcon
        uses: eProsima/eProsima-CI/ubuntu/install_colcon@v0

      - name: Install Python dependencies
        uses: eProsima/eProsima-CI/ubuntu/install_python_packages@v0
        with:
          packages: xmlschema

      - name: Setup CCache
        uses: eProsima/eProsima-CI/external/setup-ccache-action@v0

      - name: Get Fast DDS Docs branch
        id: get_fastdds_docs_branch
        uses: eProsima/eProsima-CI/ubuntu/get_related_branch_from_repo@v0
        with:
          remote_repository: eProsima/Fast-DDS-docs
          fallback_branch: ${{ inputs.fastdds_docs_branch || 'master' }}

      - name: Download Fast DDS documentation repo
        uses: eProsima/eProsima-CI/external/checkout@v0
        with:
          repository: eProsima/Fast-DDS-docs
          path: src/fastdds-docs
          ref: ${{ steps.get_fastdds_docs_branch.outputs.deduced_branch }}

      - name: Install Fast DDS Docs required python packages
        uses: eProsima/eProsima-CI/ubuntu/install_python_packages@v0
        with:
          upgrade: false
          requirements_file_name: src/fastdds-docs/docs/requirements.txt

      - name: Colcon build
        continue-on-error: false
        uses: eProsima/eProsima-CI/multiplatform/colcon_build@v0
        with:
          colcon_meta_file: ${{ github.workspace }}/src/fastdds/.github/workflows/config/documentation.meta
          colcon_build_args: '${{ inputs.colcon-args }} --packages-up-to fastdds-docs'
          cmake_args: ${{ inputs.cmake-args }}
          cmake_args_default: ''
          cmake_build_type: ${{ matrix.cmake-build-type }}
          workspace: ${{ github.workspace }}

      - name: Colcon test
        id: docs_test
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-test') }}
        uses: eProsima/eProsima-CI/multiplatform/colcon_test@v0
        with:
          colcon_test_args: ${{ inputs.colcon-args }}
          colcon_test_args_default: --event-handlers=console_direct+
          ctest_args: ${{ inputs.ctest-args }}
          ctest_args_default: ''
          packages_names: fastdds-docs
          workspace: ${{ github.workspace }}
          workspace_dependencies: ''
          test_report_artifact: ${{ format('test_report_{0}_{1}_{2}', inputs.label, github.job, join(matrix.*, '_')) }}

      - name: Fast DDS Docs test summary
        uses: eProsima/eProsima-CI/multiplatform/junit_summary@v0
        if: ${{ !cancelled() && !contains(github.event.pull_request.labels.*.name, 'no-test') }}
        with:
          junit_reports_dir: "${{ steps.docs_test.outputs.ctest_results_path }}"
          print_summary: 'True'
          show_failed: 'True'
          show_disabled: 'False'
          show_skipped: 'False'
