name: Fast DDS Ubuntu CI - ShapesDemo build

on:
  workflow_call:
    inputs:
      os-image:
        description: 'The OS image for the workflow'
        required: true
        type: string
      label:
        description: 'ID associated to the workflow'
        required: true
        type: string
      colcon-args:
        description: 'Extra arguments for colcon cli'
        required: false
        type: string
      cmake-args:
        description: 'Extra arguments for cmake cli'
        required: false
        type: string
      ctest-args:
        description: 'Extra arguments for ctest cli'
        required: false
        type: string
      fastdds-branch:
        description: 'Branch or tag of Fast DDS repository (https://github.com/eProsima/Fast-DDS)'
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  fastdds_shapesdemo_build:
    runs-on: ${{ inputs.os-image }}
    if: ${{ (
          !contains(github.event.pull_request.labels.*.name, 'skip-ci') &&
          !contains(github.event.pull_request.labels.*.name, 'conflicts')
        ) }}
    strategy:
      fail-fast: false
      matrix:
        cmake-build-type:
          - 'RelWithDebInfo'
    steps:
      - name: Download build artifacts
        uses: eProsima/eProsima-CI/external/download-artifact@v0
        with:
          name: fastdds_build_${{ inputs.label }}
          path: ${{ github.workspace }}

      - name: Install Fix Python version
        uses: eProsima/eProsima-CI/external/setup-python@v0
        with:
          python-version: '3.11'

      - name: Get minimum supported version of CMake
        uses: eProsima/eProsima-CI/external/get-cmake@v0
        with:
          cmakeVersion: '3.22.6'

      - name: Install apt packages
        uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@v0
        with:
          packages: libasio-dev libtinyxml2-dev libssl-dev

      - name: Install colcon
        uses: eProsima/eProsima-CI/ubuntu/install_colcon@v0

      - name: Install Python dependencies
        uses: eProsima/eProsima-CI/ubuntu/install_python_packages@v0
        with:
          packages: xmlschema

      - name: Setup CCache
        uses: eProsima/eProsima-CI/external/setup-ccache-action@v0

      # Get Shapes Demo to make sure it keeps compiling
      - name: Get Shapes Demo branch
        id: get_shapes_demo_branch
        uses: eProsima/eProsima-CI/ubuntu/get_related_branch_from_repo@v0
        with:
          remote_repository: eProsima/ShapesDemo
          fallback_branch: 'master'

      - name: Download Shapes Demo repo
        uses: eProsima/eProsima-CI/external/checkout@v0
        with:
          repository: eProsima/ShapesDemo
          path: src/shapes-demo
          ref: ${{ steps.get_shapes_demo_branch.outputs.deduced_branch }}

      # Required for Shapes Demo
      # Do not setup python as it will internally modify the pythonLocation env variable
      # and we want to use a fix version
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.0
        with:
          version: '5.15.2'
          dir: '${{ github.workspace }}/qt_installation/'
          modules: 'qtcharts'
          setup-python: 'false'

      - name: Colcon build
        continue-on-error: false
        uses: eProsima/eProsima-CI/multiplatform/colcon_build@v0
        with:
          colcon_meta_file: ${{ github.workspace }}/src/fastdds/.github/workflows/config/ci.meta
          colcon_build_args: '${{ inputs.colcon-args }} --packages-up-to ShapesDemo'
          cmake_args: ${{ inputs.cmake-args }}
          cmake_args_default: -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra -Wpedantic -Wunused-value -Woverloaded-virtual"
          cmake_build_type: ${{ matrix.cmake-build-type }}
          workspace: ${{ github.workspace }}
